### ISSUE TITLE
How do you process ViPC dataset and how long does it takes when training on PCN?

### ISSUE THREAD

**Issue by hangyi2000** [Hydrogenion/ViPC#10]
Could you please tell me how do you process the ViPC dataset when training on PCN and how long it takes to train PCN with the whole ViPC dataset?
Thanks a lot!

**Comment by CRISZJ** [comment]
> Could you please tell me how do you process the ViPC dataset when training on PCN and how long it takes to train PCN with the whole ViPC dataset? Thanks a lot!

it takes me about 2 weeks for each category. :-)

**Comment by Hydrogenion** [comment]
Very Very Long. Maybe 2-3 weeks.
