### ISSUE TITLE
Meaning of parameters in rendering/camera_calibration.txt file for each shape

### ISSUE THREAD

**Issue by morsingher** [Hydrogenion/ViPC#11]
Hi, thanks for open sourcing your work! I would like to get the intrinsic camera matrix for each rendered view and I have noticed there is a rendering/camera_calibration.txt file for each shape. In this file, there are three parameters, but I can't understand their meaning. Can you help me to decode such values and build the 3x3 calibration matrix?

**Comment by zhanghm1995** [comment]
@morsingher , hello, where did you find the `camera_calibration.txt` file? After downloading and extracting the dataset, I cannot find this file, could you send me this file? Thanks a lot.

**Comment by tpzou** [comment]
@zhanghm1995 Have you found the camera_calibration.txt?

**Comment by zhanghm1995** [comment]
@tpzou ，I cannot find these camera_calibration.txt files? So are you also cannot find these files?

**Comment by Hydrogenion** [comment]
In ShapeNet-ViPC, I rendered only the GT and partial point cloud.  The view data is inherited from ShapeNetRendering. For more information about ShapeNetRendering, you should check https://github.com/chrischoy/3D-R2N2 .
