### ISSUE TITLE
code cann't run directly.

### ISSUE THREAD

**Issue by doldolOuO** [Hydrogenion/ViPC#12]
code has some wrong. I have fixed some problems. Welcome to discuss with me.

**Comment by engqing** [comment]
@doldol1234 Hello, may I ask if you have successfully run this project? I encountered an error at the final step.

**Comment by doldolOuO** [comment]
utlis should be renamed utils

> @doldol1234 Hello, may I ask if you have successfully run this project? I encountered an error at the final step.

**Comment by engqing** [comment]
![image](https://user-images.githubusercontent.com/115127943/225309817-57baf870-10cb-4d58-9b83-3693ebf9c6e2.png)
@doldol1234 Thank you for your response, but the problem I am facing is with this image.

**Comment by Hydrogenion** [comment]
It seems a machine problem.

**Comment by engqing** [comment]
I understand now. Thank you for your prompt reply.

> It seems a machine problem.

**Comment by Hydrogenion** [comment]
No problem!
