### ISSUE TITLE
Meaning of parameters in rendering/rendering_metadata.txt

### ISSUE THREAD

**Issue by BlueSeaHome** [Hydrogenion/ViPC#13]
Thank you for publishing your data set!
I want to know the meaning of each column of data in rendering/metadata.txt. Each line of metadata has five values, but how can I convert them into projection matrix? Thank you very much!

**Comment by BlueSeaHome** [comment]
[rendering_metadata.txt](https://github.com/Hydrogenion/ViPC/files/10909873/rendering_metadata.txt)

**Comment by Hydrogenion** [comment]
From the left, they are azimuth, elevation, in-plane rotation, distance, the field of view.
