### ISSUE TITLE
Some questions about the dataset

### ISSUE THREAD

**Issue by engqing** [Hydrogenion/ViPC#15]
![Snipaste_2023-03-23_16-30-20](https://user-images.githubusercontent.com/115127943/227150123-35dc7c74-d081-4600-8d0c-430860cecbfa.png)
Hello, I downloaded the dataset according to the instructions, but encountered an error when training certain categories. After checking the dataset, I found that the file was indeed missing. I tried to download the dataset again, but the error still persists. Can you help me take a look? This type of error is not limited to just one category, and I am conducting experiments to investigate it.

**Comment by Hydrogenion** [comment]
Sorry for that. But I find it in my local dataset. How can I give it to you?
If you find any other missing data, please let me know and I will fix it in once.

**Comment by engqing** [comment]
![Snipaste_2023-03-23_17-19-50](https://user-images.githubusercontent.com/115127943/227208330-245ed168-3c26-41bf-ad5a-d1c121ba21a2.png)
Can you transfer it to my QQ email? 2587365706@qq.com. Besides the missing file, I also found another one. Thank you for your prompt handling.

**Comment by Hydrogenion** [comment]
Already sent to you!

**Comment by lcl124252** [comment]
> ![Snipaste_2023-03-23_17-19-50](https://user-images.githubusercontent.com/115127943/227208330-245ed168-3c26-41bf-ad5a-d1c121ba21a2.png) Can you transfer it to my QQ email? [2587365706@qq.com](mailto:2587365706@qq.com). Besides the missing file, I also found another one. Thank you for your prompt handling.

你好，我也在做这个数据集的工作，我和你一样也出现了数据集的缺失，你能把作者给你发的缺失的内容发给我一份吗？非常感谢！

**Comment by Hydrogenion** [comment]
> > ![Snipaste_2023-03-23_17-19-50](https://user-images.githubusercontent.com/115127943/227208330-245ed168-3c26-41bf-ad5a-d1c121ba21a2.png) Can you transfer it to my QQ email? [2587365706@qq.com](mailto:2587365706@qq.com). Besides the missing file, I also found another one. Thank you for your prompt handling.
> 
> 你好，我也在做这个数据集的工作，我和你一样也出现了数据集的缺失，你能把作者给你发的缺失的内容发给我一份吗？非常感谢！

Sent to you !

**Comment by lmomoy** [comment]
你好，我也出现了同样的情况，希望能够收到文件，感谢，lmomoy8@gmail.com

**Comment by caiyujiaocyj** [comment]
> > ![Snipaste_2023-03-23_17-19-50](https://user-images.githubusercontent.com/115127943/227208330-245ed168-3c26-41bf-ad5a-d1c121ba21a2.png) Can you transfer it to my QQ email? [2587365706@qq.com](mailto:2587365706@qq.com). Besides the missing file, I also found another one. Thank you for your prompt handling.
> 
> 你好，我也在做这个数据集的工作，我和你一样也出现了数据集的缺失，你能把作者给你发的缺失的内容发给我一份吗？非常感谢！

我也遇到这个问题，可以发我一份吗   987675360@qq.com

**Comment by wx-q** [comment]
Hello, I am experiencing the same issue. I hope to receive the file as well. Thank you!2997215217@qq.com

**Comment by jiang66666** [comment]
你好，我也遇到同样的问题。我也希望能收到文件。 谢谢！2425320491@qq.com
