### ISSUE TITLE
怎么把点云投影和视图相对应？

### ISSUE THREAD

**Issue by BlueSeaHome** [Hydrogenion/ViPC#17]
我们尝试过把点云进行投影，但是始终和ViPC数据集里面提供的视图对应不上。
你们能不能告诉我们怎么把点云投影到平面和视图相对应？
非常感谢！

**Comment by BlueSeaHome** [comment]
你好，能不能提供给我们你们从CAD模型渲染视图的代码？
我的邮箱2044982010@qq.com
非常感谢！

**Comment by Hydrogenion** [comment]
这部分代码请联系3D-R2N2的作者，我们继承于他们的数据集。
