### ISSUE TITLE
视图对于模型的作用

### ISSUE THREAD

**Issue by engqing** [Hydrogenion/ViPC#20]
你好，ViPC文章中研究了什么样的输入视图可以更好地辅助补全，我们注意到dataloader中似乎对不完整点云和图像进行了对齐和校准，如果要研究视图对于模型的作用，这部分的代码是不是应该注释掉？如果不注释这部分代码，输入模型的不完整点云似乎也随视图在旋转变化。

**Comment by lmomoy** [comment]
同样的问题，请问你明白了吗
