### ISSUE TITLE
ModuleNotFoundError: No module named 'point_gpu'

### ISSUE THREAD

**Issue by duzhenjiang113** [Hydrogenion/ViPC#8]

**Comment by duzhenjiang113** [comment]
could you please tell me the c++ version to compile the setup.py

**Comment by CRISZJ** [comment]
it seems that there also some error about emd loss

**Comment by duzhenjiang113** [comment]
solved it.
python3.7, gcc-7.5, pytorch1.7, cuda-11.3, kaolin v0.1
