### ISSUE TITLE
Could you please provide the pre-trained model?

### ISSUE THREAD

**Issue by RiverZhenjiang** [Hydrogenion/ViPC#9]

**Comment by Hydrogenion** [comment]
It's already in dataset cloud drive.

**Comment by CRISZJ** [comment]
Hello, the pre-trained model you provided cannot be loaded by your network. We read the parameters of the pre-trained model and found that compared with the entire ViPC network, some parameters are missing. Is our operation incorrect? Or Is the pre-trained model you provided is the part of the whole network?
